### ISSUE TITLE
Regex addressing for room broadcasts

### ISSUE THREAD

**Issue by sadmoody** [miguelgrinberg/python-socketio#1053]
Hey there, just wondering if there are any plans or appetite to add broadcasts to room via regex. I want to be able to filter rooms depending on if they match a search query.

I can currently do this by running my own search across existing rooms before passing the resulting list into `emit` - so it isn't really a blocker for my application. It seems the only modification that really needs to happen would be in `get_participants` inside `BaseManager` 

My specific application, if it helps, is for a client to be able to subscribe to signals from the server. I want the server to be able to send these signals asynchronously via websockets. These signals are hierarchical (think topic/signal). I want to be able to use rooms to keep track of subscriptions to specific topic/signal pairings so that a client only gets updated on signals (or topics) that they're interested in as opposed to a firehose of data that they otherwise don't really care about. But this means that someone who is interested in all signals under a topic, or a specific signal under multiple topics will need to explicitly subscribe to everything as opposed to just allowing for a wildcard.

Thought I'd put it out there, see if there's interest, and maybe look at porting over what I did more natively, but also I'm pretty sure no one has asked for this in the past. Saw some mentions about dynamic namespaces, but nothing really about dynamic room addressing for broadcasts. 

Thanks!

**Comment by miguelgrinberg** [comment]
No, nobody asked for this as far as I remember, and I don't believe the JS reference implementation supports this either. It's also non-trivial, I think, since this isn't just a change in `emit()`, but also in how a client joins rooms, if I understand what you want to do correctly. Joining a set of rooms given by a regex is non-trivial, since the complete list of rooms is not  easily accessible when using multiple servers.

If you use the format `topic.signal` for your rooms, then you can easily allow clients to subscribe to all the signals in a topic by joining the `topic` room. Then whenever you send a notification you send it both to the `topic.signal` room and the `topic` room, so clients will get one of them, depending on having joined the entire topic or the individual signal. Of course this does not allow a client subscribing to a given signal name under many topics, but that seems much less useful, at least that is my impression.

**Comment by sadmoody** [comment]
Cheers, yeah, it's a bit of an odd request.

To be clear, this isn't about joining a room, but about sending a message to multiple rooms. So someone can join a room called `topic.signal` and receive that pairing, or someone can join `topic.*` and they'd receive every signal under that topic.

If we're only allowing for wildcards `*` for the topic or signal name, there's a way around implementing something like this for now by explicitly passing a list of `['topic.signal', 'topic.*', '*.signal', '*.*']` - but this array will blow up as you add more levels of hierarchy (e.g. `topic.signal.1') and won't let you filter out for partial matches (e.g. `topic.signal1`, `topic.signal232' etc).

It's a very niche need and outside what's implemented in the JS reference implementation. You can get around it relatively easily (or just implement it yourself outside this library) that I don't think that it's so much of a blocker for enough people that need it for anyone to spend time on it.

More pressing things to spend time on probably!

**Comment by miguelgrinberg** [comment]
> To be clear, this isn't about joining a room
> ...
> or someone can join topic.*

Isn't this a contradiction? Here you are saying that a client can join a room given as a regex. That is exactly the use case that is hard to implement, because a server is not guaranteed to know all the rooms that exist. So you will need to keep the regex active in the system, and evaluate it every time an emit is made, which will affect performance for all emits and not only those that use this feature.

**Comment by sadmoody** [comment]
I think I mixed up two different intentions here in one go.

1. Using regex to select rooms to broadcast to
2. Joining a "catch-all" room

The first one can be useful as a way to address a subset of the rooms in a namespace - in the event that you have many rooms, or rooms created dynamically.

The second is more a result of implementing the first and isn't so important to consider here. (you can join the room `topic.*` and be caught in the regex when there's a topic-wide broadcast - but I wasn't meaning that we implement a way for someone to join available rooms given a regex)

**Comment by miguelgrinberg** [comment]
Your first topic can be implemented in the application space. You could write a `rooms_from_regex()` function that does this and then incorporate it into the emit as follows:

```python
emit('my_event', my_data, to=rooms_from_regex(my_room_regex))
```
