### ISSUE TITLE
(asgi+sanic+on_statup/on_shutdown) TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by 4n1qz5skwv** [miguelgrinberg/python-socketio#1064]
**Requirements:**
```
python-socketio==5.7.1
sanic==22.9.0
uvicorn
```

**Code (run.py):**
```python
import uvicorn
from sanic import Sanic
from socketio import AsyncServer, ASGIApp


async def on_startup(): print('on_startup!')


async def on_shutdown(): print('on_shutdown!')


app: Sanic = Sanic(__name__)
sio: AsyncServer = AsyncServer(async_mode='asgi')

app: ASGIApp = ASGIApp(sio, other_asgi_app=app,
                       on_startup=on_startup, on_shutdown=on_shutdown)

if __name__ == '__main__':
    uvicorn.run('run:app')

```

**Action:**
```curl http://127.0.0.1:8000```

- Expected Output > ```404 — Not Found```
- Actual Output  > ```Internal Server Error```

**Log:**
```
INFO:     Started server process [11796]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
on_startup!
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "X:\UserHome\venvs\lab\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "X:\UserHome\venvs\lab\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "X:\UserHome\venvs\lab\lib\site-packages\engineio\async_drivers\asgi.py", line 67, in __call__
    await self.other_asgi_app(scope, receive, send)
  File "X:\UserHome\venvs\lab\lib\site-packages\sanic\app.py", line 1316, in __call__
    self._asgi_app = await ASGIApp.create(self, scope, receive, send)
  File "X:\UserHome\venvs\lab\lib\site-packages\sanic\asgi.py", line 167, in create
    await sanic_app.dispatch(
  File "X:\UserHome\venvs\lab\lib\site-packages\sanic\signals.py", line 197, in dispatch
    return await dispatch
  File "X:\UserHome\venvs\lab\lib\site-packages\sanic\signals.py", line 135, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "X:\UserHome\venvs\lab\lib\site-packages\sanic\signals.py", line 97, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
INFO:     127.0.0.1:51047 - "GET / HTTP/1.1" 500 Internal Server Error
INFO:     Shutting down
on_shutdown!
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [11796]
```

**Note:** 
All GOOD if `on_startup=on_startup, on_shutdown=on_shutdown` is removed.
```python
app: ASGIApp = ASGIApp(sio, other_asgi_app=app)
```

**Comment by miguelgrinberg** [comment]
This isn't a bug. Sanic has a startup event handler. Because you are defining your own start up for the combined application, Sanic's does not get to run. I'm not familiar with Sanic, to tell you if this is possible, but if you need to have your own start up, then you have to figure out a way to invoke Sanic's start up handler as part of your own.

**Comment by miguelgrinberg** [comment]
@4n1qz5skwv you aren't the only one with needs regarding lifespan events. This package needs to find a balance that makes it possible to all users to do what they need to do. Please spend some time looking over the change log, so that you see that lifespan events have been actively being improved in recent releases.

If you don't like how things work now, then propose a new way that does not break any of the other use cases that the recent changes have addressed.

As I said above, your problem is easily solved, it would have taken you less time to address it than to complain and expect I should treat it as a bug and fix it. All you need to do is to call your Sanic startup function from your own startup function and that will get you back up and running.
