### ISSUE TITLE
Support for volatile messages?

### ISSUE THREAD

**Issue by am17an** [miguelgrinberg/python-socketio#115]
I have a fairly busy messaging application and sometimes the browser gets super slow if it has a big backlog of messages. Is there a way we can flag messages as volatile(i.e. okay to be dropped once in a while)? If not, is this something we can implement and/or plans to support this feature?

**Comment by miguelgrinberg** [comment]
That seems to be a request that applies to the client more than the server, correct? You would need to ask the team that maintains the official Socket.IO client for JS.

**Comment by am17an** [comment]
It seems like server-side socketIO in JS does implement volatile ( ref https://socket.io/docs/) like `socket.volatile.emit`. Correct me if I'm wrong but I think socket.io keeps track of whether the client has received the message, and setting it to volatile basically removes that check (fire and forget), so maybe this could a server side enhancement rather than client side?

**Comment by miguelgrinberg** [comment]
Oh, I see. This isn't mentioned in the socket.io specification document. I will take a look at the code to see how they have implemented it, and if it is feasible I'll add it.

**Comment by miguelgrinberg** [comment]
After looking through the Socket.IO code, it seems the way volatile is implemented is in just a single line of code: https://github.com/socketio/socket.io/blob/3b92cc2b2678f0e102d7a882248424475e7116ae/lib/client.js#L147.

This means that when the server is going to send a message, if it finds that the output buffer for the socket is full, instead of blocking and wait for the buffer to have space it just throws away the message.

Your statement:

> Correct me if I'm wrong but I think socket.io keeps track of whether the client has received the message, and setting it to volatile basically removes that check (fire and forget)

then is incorrect. This feature has nothing to do with checking if a message is received. Messages go out on a TCP connection, so all messages sent will be received, the error correction at the TCP level guarantees that. If the server is sending too many messages, then it may decide to skip some, regardless of how well or bad the client can keep up with the stream.

**Comment by am17an** [comment]
Ah I see. Thanks for taking the time out to look at it! Not a terribly useful feature indeed.

**Comment by thezboe** [comment]
I am looking for a mechanism to skip sending messages to underperforming clients or clients with underperforming networks. This looks like a good way to do that. Is there a way I can get the same effect of the volatile flag?

**Comment by miguelgrinberg** [comment]
@thezboe The volatile flag is not implemented. At the application level you can use callbacks to determine when a client is processing an event. This can be used, for example, to never send an event to a client that hasn't acknowledged the previous event via the callback.

**Comment by miguelgrinberg** [comment]
Not planning to implement `volatile` at this point. Closing.
