### ISSUE TITLE
Namespace catch-all logic

### ISSUE THREAD

**Issue by mooomooo** [miguelgrinberg/python-socketio#1334]
I think the handling of the namespace catch-alls is a bit unintuitive right now.  In particular, if you create two handlers:
- ns = *, event = e1
- ns = n, event = e2

then sending a message to ns = n, event = e1 gets dropped instead of getting picked up by the catch-all.  If that's not an intentional choice, I think it'd make more sense for the logic to not be nested as it currently is, and instead just a sequence of checks, i.e.:

```
        if namespace in self.handlers and \
                event in self.handlers[namespace]:
            handler = self.handlers[namespace][event]
        elif namespace in self.handlers and \
                event not in self.reserved_events and \
                '*' in self.handlers[namespace]:
            handler = self.handlers[namespace]['*']
            args = (event, *args)
        elif '*' in self.handlers and \
                event in self.handlers['*']:
            handler = self.handlers['*'][event]
            args = (namespace, *args)
        elif '*' in self.handlers and \
                event not in self.reserved_events and \
                '*' in self.handlers['*']:
            handler = self.handlers['*']['*']
            args = (event, namespace, *args)
        else:
            handler = None
```

instead of the current:

https://github.com/miguelgrinberg/python-socketio/blob/547449bc70248b1a2c68e362a026d42db083222c/src/socketio/base_server.py#L222-L236

**Comment by miguelgrinberg** [comment]
Looks look at the example you suggested in detail:

- ns = *, event = e1
- ns = n, event = e2

When you send an event to `ns = n, event = e1` this happens:

- the conditional in line 222 of base_server.py is `true`
- the conditional in line 223 is `false`
- the conditional in line 225 is `false`
- the conditional in line 229 is `true`
- the conditional in line 230 is `true`, and the event is dispatched to the e1 handler in the catch-all namespace

So I don't really see what the problem is.

**Comment by mooomooo** [comment]
Hm yes you're absolutely right, somehow I read the condition in line 229 as an elif, and I didn't pay close enough attention to whatever testing I was doing.  Never mind then.
