### ISSUE TITLE
need clarifications regarding Client Managers and multiple processes

### ISSUE THREAD

**Issue by ckot** [miguelgrinberg/python-socketio#219]
Hi, I'm creating a Django app which I'm planning to deploy with nginx + uwsgi, and make use of KombuManager for supporting multiple processes. 

According to your docs, to support multiple processes, 'sticky' sessions  should be used by the load-balancer ('ip_hash' in nginx).  Would I be correct in understanding that it's the 'process' we want to be 'sticky' about, not the port, so if I want to deploy my app using multiple uwsgi instances, each on different port, each of these instances should be configured to use a single process, right?

Although `Server`s API provides `rooms(sid, namespace)`, I didn't see any way to query what users where in what rooms.  I was in the process of writing wrapper code `ChatRoomManager(sid)`, which uses redis to maintain the global list of sids, rooms, and who is in them, etc.  When I discovered `BaseManager::get_participants()`, it made me think my code was entirely unnecessary.  However, according to a quick look over the code (drilling down the chain from BaseManager -> KombuManager),  I noticed that BaseManager's  'rooms' dict doesn't ever seem to get re-implemented in a more 'distributed' fashion. This means that each wsgi instance would only be aware of it's own sids/rooms, and thus `BaseManager::get_participants()` wouldn't be reliable for my uses, and that I'm on the right track by maintaining this data at the application-level (in my case redis)? 

Meaning that, If I configure things as:
```
    kombu_mgr = socketio.KombuManager(...)
    sio = socketio.Server(client_manager=kombu_mgr, ...)
```
my wrapper class should use the 'sio' reference rather than the 'kombu_mgr' reference, despite it's more attractive extended API (don't treat it as a public API)?  

Am I correct in understanding that when using a client manager, all of the processes will get notified on a sio.emit() since they all subscribe to a message queue, but only processes for which the sid/room/namespace/whatever is local will pay attention to it/pass it along to clients?

And, *finally*, if a user closes the tab/browser/navigates to another page, will a `disconnect` event automatically be received by the associated process? I notice that their is a 'ping_timeout' which clients use, but I see any reference to a setting where the server/engine auto-disconnects users it hasn't received a ping from recently.

**Comment by miguelgrinberg** [comment]
> Would I be correct in understanding that it's the 'process' we want to be 'sticky' about, not the port, so if I want to deploy my app using multiple uwsgi instances, each on different port, each of these instances should be configured to use a single process, right?

That is correct. You can run several uwsgi processes, each on a different port, and have nginx use sticky sessions to load balance among them. What you cannot do is launch multiple processes from a single uwsgi master, because uwsgi does not currently have sticky session support (though this feature is coming soon I believe).

>  I didn't see any way to query what users where in what rooms.

No, that is not available and is by design. You can't also ask for a complete list of users. Your application can handle this much better than this package, which has no idea what a "user" is or means.

> I noticed that BaseManager's 'rooms' dict doesn't ever seem to get re-implemented in a more 'distributed' fashion

No. The `get_participants()` method is intended to return only the users that are known to the server, not the complete list. I think I need to document that, this should be in the docstring.

> Am I correct in understanding that when using a client manager, all of the processes will get notified on a sio.emit() since they all subscribe to a message queue, but only processes for which the sid/room/namespace/whatever is local will pay attention to it/pass it along to clients?

Something like that, yes. Emits are sent to all subscribers, and each process will run it locally on its client list. For some processes the emit may do nothing (for example, if none of the clients attached to that process are in the requested room).

>  if a user closes the tab/browser/navigates to another page, will a disconnect event automatically be received by the associated process?

Yes. For WebSocket clients the disconnect happens almost immediately. For long-polling clients you will get the disconnect up to a minute later if you use the default timeout of one minute.
