### ISSUE TITLE
does the client code work for https?

### ISSUE THREAD

**Issue by elsampsa** [miguelgrinberg/python-socketio#222]
Hi,

I'm trying to connect with a python-socketio **client** to a **https** (javascript) socket.io server using this sample code:
https://github.com/miguelgrinberg/python-socketio/blob/master/examples/client/asyncio/latency_client.py

I'm getting immediate disconnection from the secure **https** server.  Is the python-socketio client part good for secure **https** connections ?  I just wanted to ask this first before giving more details logs and stuff .. just to know I'm not chasing ghosts here.

Regards,

Sampsa

**Comment by miguelgrinberg** [comment]
You are using code that hasn't been officially released yet, so I can't really say. I'm not done with this work yet. In theory https should work, but haven't done a lot of testing, specially against the reference server in JS.

**Comment by miguelgrinberg** [comment]
I just tested the client against a JS socket.io server and sure enough, there appears to be a problem. I don't think it is related to https though, I get a websocket connection error on regular http. The sync client example in the threads directory connects just fine. I'll look into the problem, the sync and async clients are nearly identical, but the websocket libraries that I'm using for each are different, maybe the problem is there.

**Comment by elsampsa** [comment]
I don't know if it has anything to do with this, but ..
- My problem with your client implementation is, that an https connection drops mysteriously
- I started to work on my own client, and could reproduce the issue when ..

I start a message to the server with
```
42
```
Then it should continue
```
42["call",{"key":value, ..}]
```
And everythings fine, but if I use, for example (observe the extra ","):
```
42,["call",{"key":value, ..}]
```
Then the server will quietly drop the connection.

Don't know if this helps.  Might be specific to my case.
