### ISSUE TITLE
mix of OPP and sio.on('message')

### ISSUE THREAD

**Issue by eeerrrwwwuuu** [miguelgrinberg/python-socketio#293]
It looks like this library has some problems in multi threading environment.

I have class

```
class X:

self.got_response = False

def gotConnection(self):
      print("Connected")

def gotMessage(self, data):
      print("Data : ", data )
      self.got_response = True

def startSocket(self):
     self.sio =  socketio.Client()
     self.sio.on('connect', self.gotConnection )
     self.sio.on('message', self.gotMessage )
     self.sio.wait()

def worker(self):
      while True:
           <some processing > 
           self.sio.emit('message', <some message>)

           self.got_response = False

           while not self.got_response:
                    ### expecting emit('message', 'response' ) from server 
                    ### server is emitting message,  but getMessage is not called !
                    print("Waiting for response")

```
later I call two threads to deal with so
```
... within main: 
x = x()

th = threading.Thread(target=x.startSocket)
th.daemon = True
th.start()

th2 = threading.Thread(target=x.worker)
th2.daemon = True
th2.start()

while True:
    time.sleep(0.001)
    pass

```
It looks like message event is not working in that configuration, I do get "connect" output but not "message" . I though that it's connected with "self" passed to method, but removing it doesn't change anything.

**Comment by miguelgrinberg** [comment]
@eeerrrwwwuuu are you using an async framework such as eventlet or gevent? There are a few problems with your implementation that at best would make your application slow and inefficient, or completely blocked at worst. If you have in fact eventlet or gevent installed then I'm not surprised nothing seems to work, since you have a few blocking while-loops in there.

As a high level note, you have two tasks, but you are running three threads (main plus two background threads). A better use of resources would be to run one background task and the other in the main thread. I recommend that you move the Socket.IO client to the main thread.

In your main thread you do this:

```python
while True:
    time.sleep(0.001)
    pass
```

This is a busy loop, the code is spinning on this loop at a fast speed while doing nothing except using up CPU cycles. Either move the Socket.IO client to this thread, or else make it sleep for longer, since there is really no point in iterating at fast speed here. If you decide to keep this loop, make it a `sleep(1)`, for example. Also, I recommend that you use `sio.sleep(1)` here, because this function uses the correct method of sleeping based on the async framework that you are using. The `time.sleep()` function should not be used with eventlet or gevent as it is blocking.

Then in your worker thread you have this:

```python
           while not self.got_response:
                    ### expecting emit('message', 'response' ) from server 
                    ### server is emitting message,  but getMessage is not called !
                    print("Waiting for response")
```

This is actually even worse, because this loop does not have a sleep. It will spin at full speed with high CPU usage. Add a `sio.sleep(1)` or maybe `sio.sleep(0.1)` to prevent the loop to steal all your CPU cycles.

If what you do in the `<some processing>` place takes too long, you will need to add `sio.sleep(0)` calls to allow other tasks to run. This is necessary if you are using eventlet or gevent only.

That's all I can find. If after making the changes above you do not see an improvement, then you should get logs from the client and the server to see what's going on. To add logs to the client add `engineio_logger=True, logger=True` to the `Client()` class. If you are using the python Socket.IO server, add the same arguments to the `Server()` class.

**Comment by eeerrrwwwuuu** [comment]
Thank You very much for You time spent on reply, well it's my first app on Python and it's more about computer vision so full usage or CPU/GPU is really wanted here. I'll try to follow Your guidelines and let You know about progress.
Regards!

**Comment by miguelgrinberg** [comment]
@eeerrrwwwuuu in general CPU heavy tasks do not work well with asynchronous servers. A common pattern is to use separate processes for the CPU heavy work and the server, and have them communicate either through a network socket or a message queue.

**Comment by eeerrrwwwuuu** [comment]
Well, I have separate script which uses TensorFlow ( 5 Gig GPU process ) and ramdisk + socketIO to exchange frames between input camera processes ( 4 cameras, one GPU process ). I've changed a bit code to make sio global, I also use global flag which exchange information about response and it seems to work. ;)  Time will tell, I know that it's poor quality of code but on daily bases I work with Data Warehouses and Business Intelligence so it's something new for me... anyway If I'll be successful someone else will rewrite it according to "good standards" ;) One more time THX!
