### ISSUE TITLE
How to get a list of all rooms?

### ISSUE THREAD

**Issue by alexfanchina** [miguelgrinberg/python-socketio#297]
Is there any way to get all the rooms?

**Comment by Avinash-Raj** [comment]
Yes, you could. Try this,

`sio_serverobj.manager.rooms`

**Comment by miguelgrinberg** [comment]
This is accessing the internals of this package, which are subject to change at any time. I make no guarantees that this is going to be preserved in future releases.

The list of rooms is actually not provided, because when you scale the server to multiple workers it is not trivial to obtain the full list. The application is actually in a much better position to keep track of the active rooms, maybe in a database, something this package does not have access to.
