### ISSUE TITLE
nodejs application can't get event

### ISSUE THREAD

**Issue by getmonyinfo** [miguelgrinberg/python-socketio#306]
server.py
```py
from aiohttp import web
import socketio
from urllib.parse import urlparse, parse_qs
import random
import time

sio = socketio.AsyncServer(logger=True)
app = web.Application()
sio.attach(app)

@sio.event(namespace='/launch')
async def connect(sid, environ):
    await sio.emit('message', {'data':'new message'}, room=sid)

@sio.event(namespace='/launch')
def disconnect(sid):
    pass

if __name__ == '__main__':
    web.run_app(app, port=3000)
```

launch.js
```js
var io = require('socket.io-client');
var os = require('os')
const { spawn } = require('child_process')

var socket = io(`http://192.168.10.162:3000/launch?host=${os.hostname()}`,{
    transports: ['websocket'],
    upgrade: false,
});
socket.on('connect', function() {
    console.log('connect')

})
socket.on('message', function (data) {
    console.log('message event')
})
```
in `launch.js` the message event is not `fired`

but rewrite the server code in nodejs, that works fine
```js
const server = require('http').createServer();
// https://github.com/socketio/socket.io/issues/3259
const io = require('socket.io')(server, {
    pingTimeout: 60000,
  });

io.set('transports', ['websocket'])


var launch_users = {}

var launch = io.of('/launch')
launch.on('connection', function(client) {
    // console.log(socket.conn.transport.name)
    launch.emit('message',{})
})

server.listen(3000, "0.0.0.0");
```

so what's the problem??????

**Comment by adelespinasse** [comment]
I think I'm having the same problem. I've tried both aiohttp and tornado with AsyncServer.

I also am returning a response from a message handler in AsyncServer, and the callback on the Node.js client never gets called.

I have both client and server in both Python and Node.js. The JS server works with both clients. The Python server works with the Python client but not with the Node.js client.

I've been snooping on the network traffic with tcpflow, and as far as I can tell the response is never even sent by AsyncServer, which is weird because the response does get sent when the client is in Node.js.

**Comment by adelespinasse** [comment]
Or maybe my problem is not the same. When I force the client to use only the websocket transport (which you're already doing), it works for me.

**Comment by miguelgrinberg** [comment]
@getmonyinfo Try this:

```python
@sio.event(namespace='/launch')
async def connect(sid, environ):
    await sio.emit('message', {'data':'new message'}, room=sid, namespace='/launch')
```

The namespace needs to be specified in the emit call. You can also create a class-based namespace, and then the emit method in the namespace class is pre-configured for the correct namespace.
