### ISSUE TITLE
wss://url:port is not an accepted origin.

### ISSUE THREAD

**Issue by ffleandro** [miguelgrinberg/python-socketio#351]
Recently I've started to see the following error when connecting using the `socket.io-client-swift`. Connecting using `socket.io-client-java` works fine.

```
wss://myip:port is not an accepted origin.
```

Using:
```
Name: Flask-SocketIO
Version: 4.2.1
---
Name: python-engineio
Version: 3.9.3
```

**Comment by miguelgrinberg** [comment]
This is because the client that you are using is setting the `Origin` header. Normally it is only web browsers that set it. See if you can configure your client to not include the `Origin` header in the connection request, or else add the `cors_allowed_origins` option to your server so that this origin is accepted.
