### ISSUE TITLE
Asyncio client hangs

### ISSUE THREAD

**Issue by hamidb80** [miguelgrinberg/python-socketio#432]
Hi.

I started to use "asyncio client" instead of "threading client" .

But now I have some problems:
1. Every event expect "connect" has a delay on receiving event about 2 secs ( on my friend's computer it's about 10 secs or more). 

2. I have the same problem on emitting events. 

All things works perfectly on "threading client" . 

Python: 3.8

**Comment by miguelgrinberg** [comment]
Bit of advice. If you expect help, it's probably not a good idea to claim that the project you are trying to get help on "sucks". 

Please provide example code I can use to verify your delay. Or instructions to reproduce this problem using any of the examples in this repository. How would you feel if I were to claim that the way you report problems also sucks? Please try to be civil. The person on the other side is a human, not a machine.

**Comment by hamidb80** [comment]
Can you test it or should I give you a simpler code? 

I appreciate your responsibility. 

https://github.com/hamidb80/super-admin/tree/master/client

**Comment by miguelgrinberg** [comment]
@hamidb80 I think you need to review more carefully the rules for writing an asyncio application. Unfortunately your application is not trivial to run, but looking at it I see that you are using threads and the `time.sleep()` function, so my guess is that these two are blocking the asyncio loop somehow. Why are you using threads on an asyncio application? In general it is not a good idea because it is hard to mix threads with an asyncio loop. Most people run non-asyncio code in a thread or process executor pool to avoid problems.
