### ISSUE TITLE
Howto: Create multiple socket

### ISSUE THREAD

**Issue by bhakta0007** [miguelgrinberg/python-socketio#466]
I am  using Celery based workers for doing background tasks. The background tasks need to connect to socketio server for sending updates and notifications. As of now I have a single celery worker node (running eventlet)

Ideally, I would like to create one socketio client instance per worker task , do the task, and tear it down at the end, but I am guessing this would be a problem as the socketio needs a thread to maintain the connection. Is my understanding correct?

What is the right way to do this?

few options:

1. Create one global websocket connection per celery worker . All tasks to use this - The part I need to handle is demux of messages among the celery tasks  and that might get messeir

2. Create prefork workers on celery (but this might be overkill as the tasks are not lightweight)

3. Any other options?

**Comment by miguelgrinberg** [comment]
You are over-thinking this. The server holds the WebSocket connections. The workers use a "write-only" Socket.IO instance to send updates to clients, via the server. See the [documentation](https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process).

**Comment by bhakta0007** [comment]
I am probably over thinking this - 
In my case, I have built a message framework (bi-directional) using websockets.

The server is like a hub and clients are the spokes. Server routes messages between clients, making bi-directional messaging possible between clients. I have also built a mechanism to send a message and wait for a response. 

The client (worker) needs to send message, and wait (in this case sleep till the async response arrives or a timeout happens). I am probably getting confused as to how the async response will arrive back while the worker is waiting for it (unless there is another thread to receive the response).

I need to think about this a little I think

**Comment by miguelgrinberg** [comment]
You are definitely overthinking it. If you've built your own messaging framework then that's really it, I'm not sure what's the point of you looking at this package since you have your own thing.

Now, if you want to implement your messaging with this package then there are three different entities:

- the server(s): these hold the WebSocket connections to clients
- the clients: these connect to the server
- the write-only auxiliary processes: these run close to the server. They communicate with the server through a message queue (redis, rabbit, etc.)

What you can do:

- Servers can emit to one client, a group of clients (a room) or all clients (a broadcast). They can receive from clients as well.
- Clients can emit and receive to/from the server.
- Write-only processes can only emit.

Emits are always asynchronous. You can get a response via callback, or you can use the `call()` method to run the emit and wait for a response. The complexities of waiting for the response are handled internally by `call()`.

**Comment by bhakta0007** [comment]
I have built the messaging using this package. b.t.w where is this call() method documented? I just looked at the client side documentation but could not locate the call() 
https://python-socketio.readthedocs.io/en/latest/client.html
