### ISSUE TITLE
AsyncClient gives `Unexpected error decoding packet: "'WebSocketError' object has no attribute 'encode'"` when the server emits large file

### ISSUE THREAD

**Issue by secretlyvogon** [miguelgrinberg/python-socketio#479]
I am trying to send a large file along with some string as data to 3 clients. The code I have written was working earlier when I was sending a file which was around 20-30 KB. Now I want to use the same code to send a file which is of 55 MB. I get the aforementioned error after enabling engineio logs. 

In the future, I may need to send even larger files which are about 200 MB to various clients. How should I do that?

**Comment by miguelgrinberg** [comment]
I need to see the stacktrace of the error to know more, but you may have hit an issue and/or limitation in the websockets package.

**Comment by secretlyvogon** [comment]
I do not get an error, the process simply hangs (perhaps because of `socket.wait()` statement). I get the message above through engineio logger. From what I can understand by looking at the engineio code corresponding to the message is that instead of sending the data, the server is perhaps sending an object of type `WebScoketError` However, if I run the server with logging enabled, I can see the entire data in encoded format appear on the console. The console output takes a bit to display the entire message, meanwhile the clients disconnect (time out) as they don't receive any PONG data from the server. 

I hope this information is helpful.

**Comment by miguelgrinberg** [comment]
Oh, I see. I missed the "Unexpected error decoding packet" prefix. Yes, this is an error that I'm catching. So it seems the websocket client is returning this `WebSocketError` object instead of the actual data.

Would you feel comfortable making a small change to hopefully obtain a bit more info? This error is put out by the python-engineio's asyncio_client.py file, in lines 518-519:

```python
                self.logger.info(
                    'Unexpected error decoding packet: "%s", aborting', str(e))
```

If you can locate this statement in your virtualenv (or if you prefer to do a source install, up to you), it would be useful to also show the `p` object:

```python
                self.logger.info(
                    'Unexpected error decoding packet: "%s", p=%s, aborting', str(e), str(p))
```

Hopefully this `WebSocketError` object will include some error message that is more meaningful.

**Comment by bhakta0007** [comment]
I had a question on this topic - since we are talking about sending files.

Q: Can I use websocket to **reliably** send large files (say 200-400Meg)?  I remember seeing an issue (though I cannot recollect the exact issue at this time) with large files that I ended up creating a logic to chunk the files to 1Mb chunks and then put them back together on the receiver.

After seeing this thread - I am wondering If i need to re-visit that piece of code to see if I fundamentally missed something and If I really need that chunking logic at all?

**Comment by miguelgrinberg** [comment]
@bhakta0007 I would not rely on large transfers. The larger/longer the transfer is, the more likely a random disconnection will invalidate the entire transfer. File transfers in most protocols use chunks and can resume after a reconnection from the point of interruption. In my opinion what you did is better than sending in a single message.

**Comment by secretlyvogon** [comment]
@miguelgrinberg sorry for taking long. I ran the code with the suggested changes and as suspected, it is a size problem. The error says:

`"'WebSocketError' object has no attribute 'encode'", p=Message size 86363235 exceeds limit 4194304 aborting`

As you mentioned above, a strategy to transfer my files in chunks would make more sense for this specific problem? 

While performing other tests I ran into another error message. When I have heavy (synchronous) computations to perform on the client-side which take time, the server gives out `Receive error -- socket is closed` and the connection has to be re-established. On the client side I would get the following error from the logger:

` "'int' object has no attribute 'encode'",p=1000`

I understand this could be because the client fails to send PING messages to the server and hence the server may assume that the socket is closed. Is there a way I could tell the server to keep the connection open for longer? I tried `ping_timeout`, `ping_interval` and `request_timeout` but without any avail.

**Comment by miguelgrinberg** [comment]
Definitely better to transfer a large file in chunks.

You can't do heavy computations on the server. That's what causing the clients to drop indirectly. The clients are sending their pings, but the server is blocked doing computation and cannot process them. This is an asynchronous server, sync code is incompatible.

**Comment by secretlyvogon** [comment]
@miguelgrinberg I just noticed I pasted the wrong error message (sorry for that). The server side emits: `Client is gone. Closing socket` and not `Receive error -- socket is closed` 

As I mentioned, the client is the one performing synchronous computation. In that case, it is unable to send the PING.

**Comment by miguelgrinberg** [comment]
Oh, sorry, assumed it was the server doing the computation. Given that you are using the async client the same rules apply with regards to computation. But on the client you have options. You can use the sync client, which is multithreaded.

**Comment by secretlyvogon** [comment]
Okay thanks! Multithreading should work for me. Closing the issue.
