### ISSUE TITLE
Pass connection headers as function

### ISSUE THREAD

**Issue by ikhz** [miguelgrinberg/python-socketio#588]
There is a case to pass auth headers on connection/reconnection eg jwt, in current implementation headers are fixed, but jwt access token can change during period of time between connection and further reconnection so reconnection attempts will be unsuccessful. It can be solved by passing headers as function that get actual values for headers (fresh tokens)

**Comment by miguelgrinberg** [comment]
The headers that are going to be used when reconnecting are kept in the `connection_headers` attribute. Perhaps it would be more efficient to add a public method to make an update to this dictionary, so that when/if you renew your token you can update it in the client so that it is ready to be used in the case of a disconnection.
