### ISSUE TITLE
How to properly set up socket event listeners on a for loop?

### ISSUE THREAD

**Issue by Dwyte** [miguelgrinberg/python-socketio#620]
## What I have tried so far...
This is not the exact code that I tried but the approach can be simplified to this just for the example...

```py
# boilerplate code here...

for num in range(4):
    @sio.on(f"event_{num}")
    async def on_event(message):
        print(num)
```

## Listeners
- event_0
- event_1
- event_2
- event_3

## Problem
All of these gets listened properly but all of them uses the last one's handler instead of their own. For example if it receives **event_0** it should print **0** right, but it doesn't, it prints **3** instead which is the handler for the last one event_3.

## Question
So how can I do this? Because I am setting the event names from a config file and I don't want to add extra lines of code and would be harder to maintain. The handlers are very similar on what they do just different on that number thing that I'll be setting on the config like from the example above.. Thanks!

**Comment by miguelgrinberg** [comment]
@Dwyte this is a problem with Python scoping rules, as far as I can see your event handlers are all correct. The problem is that there is a single variable `num`, which in the context of your code it has a value `3` because that's the value it keeps when the loop ends.

Basically what you need to do is bind the value of `num` to the event handler function. Here is one way to do it, using `functools.partial`:

```python
from functools import partial

async def on_event(num, message):
    print(num)

for num in range(4):
    @sio.on(f"event_{num}", partial(on_event, num))
```

Disclaimer: I haven't tested the code above, I wrote it from memory. It may need some adjustments to run, but hopefully you get the idea!

**Comment by Dwyte** [comment]
@miguelgrinberg  it works now, thanks for the help!
