### ISSUE TITLE
Connection Error with Meaningless Traceback

### ISSUE THREAD

**Issue by WhymustIhaveaname** [miguelgrinberg/python-socketio#625]
I connect my socketio client to my socketio server. It quits with
```
Traceback (most recent call last):
  File "./FSMClient.py", line 592, in <module>
    fm.connect()
  File "./FSMClient.py", line 199, in connect
    self.sio.connect(self.url)
  File "/home/spinor/.local/lib/python3.6/site-packages/socketio/client.py", line 283, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Connection refused by the server
```
This is meaningless. Python-socketio should provide more information for debugging. I confirmed that the socketio version of server and client are the same, both 4.6.0. I also read the codes in `"/home/spinor/.local/lib/python3.6/site-packages/socketio/client.py", line 283`, still no clue.

**Comment by miguelgrinberg** [comment]
The error is exactly what the message said. The server did not accept the connection. How can that be made more clear? It seems you are looking for the problem in the client. That is the wrong place to look.

**Comment by WhymustIhaveaname** [comment]
Thank you for your quick reply. We have solved the problem. Although we were cautious about keeping the socketio's version be same, the engineio's version is different! After we downgrade the version of the client, all errors disappeared. However, I have some suggestions for python-socketio:

* A mature software should be backward compatible, not change protocol every time upgrading. We have known that socketio will not work if server version and client version are not compatible. But many people do not know, and a huge number of hours have been wasted just for solving this simple problem.
* A mature software should be self-complete. It should not relay its main function on other projects and even crash after other projects' updates. In this case, how could one know that this is actually the problem of eigineio? Again, in this case, we find that eigineio is written by the same author as socketio. So I hope you to be self-consistent when writing codes. Please do not change it after it is published. Or at least make it backward compatible for one main version.
* A mature software should have meaningful logs. I check both the log of the server and the client yesterday. The server's log is even shorter. It said it received a message from the client and no more. For this case, the log should be `Connection refused by the server. Please make sure the version of socketio and eigeneio on server and client be same`. You blame me for not reading debugging/troubleshooting. But will your debugging/troubleshooting have the answer for such a wired problem? So I have the last suggestion.
* A mature software should not blame users for its spaghetti code.

**Comment by miguelgrinberg** [comment]
> A mature software should be backward compatible, not change protocol every time upgrading

I agree. But you need to talk to the people who design the Socket.IO protocol and the reference JavaScript implementation about this, which is not me. I just follow the spec to be compatible with them. If you think I like to take heat from you and a lot of other people, you are mistaken, if it was up to me everything would be backwards compatible.

> It should not relay its main function on other projects

No idea what you mean here. What other project(s)?

> and even crash after other projects' updates

I agree. The project should not crash, ideally. Though as far as I can see in your description it didn't, it just returned an error that to me appears decent, given than you appear to have been using a version of python-engineio that isn't compatible with python-socketio. It is difficult to preview every possible wrong combination of dependencies and have error control for all of them though. Part of it is your fault. The range of versions that are compatible with each other are documented.

> Please do not change it after it is published. Or at least make it backward compatible for one main version.

Yeah, but once again, talk to the Socket.IO people, I have nothing to do with the decisions they make about the direction of the Socket.IO protocol.

> For this case, the log should be Connection refused by the server. Please make sure the version of socketio and eigeneio on server and client be same

I disagree. A connection refused is a good description of the error from the client's point of view. Rejecting a connection is a supported action for the server, and in most cases it happens due to failed authentication. Having a mismatched set of dependencies is a corner case that confuses the code only because you mistakenly installing incompatible versions.

> You blame me for not reading debugging/troubleshooting

I blame you for not adding your logs to your report, which would have likely helped me identify the problem very quickly.

I also blame you for starting this report in a somewhat aggressive manner, with your claim of "meaningless logs". Because you started with that tone, I now also have a tone in my responses, and nobody benefits when we interact in this way.

> You blame me for not reading debugging/troubleshooting. But will your debugging/troubleshooting have the answer for such a wired problem?

The log would have detected incompatible versions of client and server. It would not have detected incompatible versions of socketio and engineio in the same side, which is the problem that you had. How did you end up with an incompatible set of dependencies? Because that's really the problem here. We should be discussing that more than anything else.

> A mature software should not blame users for its spaghetti code.

Nice. Very classy.

**Comment by WhymustIhaveaname** [comment]
Sorry for my tone. I install my socketio on both server and client by pip3. Pip3 find suitable version and installed dependency for me. Then I found the socketio version on server is low, maybe because I am using Aliyun as server and Aliyun force me to use its mirror. So I downgrade the version of socketio on client manually. For a long time I do not know the exsit of eigeneio.

**Comment by WhymustIhaveaname** [comment]
The problem was solved after I found I can set my own logger in socketio and see more logs. Then I know socketio uses eigeneio for communication. Then I check the version of eigenio and the problem solved.
