### ISSUE TITLE
The redis support is incompatible with the socket.io-redis/emitter javascript one

### ISSUE THREAD

**Issue by gcbirzan** [miguelgrinberg/python-socketio#68]
The 'protocol' is 'described' (read implemented) in this [file](https://github.com/socketio/socket.io-emitter/blob/master/index.js). It would be useful to both handle messages coming from socket.io-emitter, and be able to emit towards socket.io-redis.

**Comment by miguelgrinberg** [comment]
Is there really a use case for this? All the JS emitter does is collect all the arguments of the emi, put them in a JS object, then serialize it with msgpack and publish it on a given channel. If you want to use Python to emit to a Node Socket.IO server, using this project would be overkill, since all you need is to publish a dict with 3-4 values to a Redis channel. And the reverse holds true as well. If you wanted to emit from JS (or any other language) to a Python Socket.IO server, it would be fairly easy to publish on the Redis channel the required data.

Is there a use case that I'm missing?
