### ISSUE TITLE
Not every messages are sent from server

### ISSUE THREAD

**Issue by koustuvsinha** [miguelgrinberg/python-socketio#7]
Hi! I headed to this library after an unsuccessful attempt with Flask SocketIO, yet the same problem remains. I am trying to display real time tweets through sockets connection, but I am unable to do so. Here is the server implementation : 

```python
@sio.on('handshake')
def handshake(sid,data):
    print('handshaked!')
    print(sid)
    client_sid = sid
    sendMessage("Starting to connect with Twitter")
    sendMessage("...")
    startStreaming()
    sendMessage("Started streaming...")

def sendMessage(message):
    print 'sending message' + message
    sio.emit('message',{"data" : message})

def startStreaming():
    sendMessage("Connected")
    ts = TwitterStream(auth=OAuth(token_key,token,con_key,con_secret))
    iterator = ts.statuses.filter(follow=37034483)
    for tweet in iterator:
        tweetBody = json.loads(json.dumps(tweet))
        print(tweetBody["text"])
        sendMessage(tweetBody["text"])

if __name__ == "__main__":
    app = socketio.Middleware(sio, app)
    eventlet.wsgi.server(eventlet.listen(('', 5000)),app)
```

And the client is a simple listener : 

```javascript
var socket = io.connect('http://' + document.domain + ':' + location.port)
  socket.on('connect', function () {
      socket.emit('handshake', { data : 'connected'})
  })
  socket.on('message', function (tweet) {
    console.log(tweet)
    $(".messages").append("<p>" + tweet.data + "</p>")
  })
```

Now the issue is that, after initial `handshake`, the server is posting the first two messages "Starting to connect with Twitter" and "...", but soon after it doesn't even post the subsequent messages, not even "Connected", and the logs show that I am receiving twitter streams. I have tried every iteration, and even using Flask SocketIO global broadcast `socketio.emit` but of no use. Please suggest alternatives. (P.S. I am new in python)

**Comment by miguelgrinberg** [comment]
First of all, you have to monkey patch the standard library so that it plays nice with the coroutine model of eventlet (if you haven't done that already). Just call `eventlet.monkey_patch()` at the very start of the application, before all your other imports.

The second problem is that you are never returning control back to the framework when the server receives the `handshake` event. Because eventlet is a coroutine framework, it depends on all the tasks releasing the CPU. Your `handshake()` function calls `startStreaming` and never returns or releases the CPU, so no other coroutine will be able to run, which means that no other messages will go in or out.

A quick hack that may allow you to start sending and receiving messages is to add a `sleep(0)` inside the for loop in `startStreaming()`. Each time you sleep, it gives other coroutines the opportunity to run.

A much much better solution, though, would be to have the `handshake()` function run `startStreaming()` as a background task, so that it can return immediately without blocking the framework.

**Comment by koustuvsinha** [comment]
great in-depth explanation! and it worked after I had added a background thread :+1: thanks a ton!
