### ISSUE TITLE
Asyncio Protocol support

### ISSUE THREAD

**Issue by Superman132** [miguelgrinberg/python-socketio#70]
I was wondering if their would be a way to start a socket.io server with asyncio protocol. Right now I believe the server is only compatible with [aiohttp](https://github.com/KeepSafe/aiohttp), but I hope to be able to use it with [Sanic](https://github.com/channelcat/sanic) or standalone.

**Comment by miguelgrinberg** [comment]
My understanding is that Sanic does not support WebSocket, so isn't it a moot point at this time?

**Comment by miguelgrinberg** [comment]
@Superman132 I have added support for sanic long-polling now. To try this, you need to get the master branch of python-engineio. I've added a couple of sanic examples in this repo.

Unfortunately, only long-polling works right now, since there is no WebSocket support directly available via Sanic. I may look into using a separate WebSocket implementation when I get some time.

**Comment by Superman132** [comment]
Thanks, I will definitely try this out :). I appreciate it.
