### ISSUE TITLE
multiple namespaces

### ISSUE THREAD

**Issue by blaisezzz** [miguelgrinberg/python-socketio#73]
I am relatively new to both Python and Socket IO library. The test sample provided was a treat to work with, and I am looking to extend beyond the sample code provided. I was wondering if you can help me out with connection to multiple namespaces. What I mean is I would like to group together clients in rooms as well as namespaces. It would be awesome if I am able to directly communicate to multiple clients regardless which namespace or rooms they are in. 

Ideally, what what I want to do is to give the client the option to go into the namespace and a room after they connect. Then, I want to send a message to specific clients that are in the same room and same namespace. How would I go about achieving that ?

**Comment by miguelgrinberg** [comment]
Namespaces are not meant to be used in that way. The idea of namespaces, as defined in the Socket.IO specification, is to allow multiple applications to make logical connections to a server, all multiplexed in a single physical connection. A client needs to specify what namespace it wants to connect to, there is no way to "bridge" two namespaces, since they are supposed to be completely independent connections.

My recommendation is that you use the rooms feature to create all the groupings of clients that you need. Rooms are actually fairly cheap on the system, so you can create as many as you need.

**Comment by blaisezzz** [comment]
Miguel,

That was helpful. Thank you!
