### ISSUE TITLE
Support msgpack as an event encoding alternative to JSON

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/python-socketio#749]
msgpack support for the reference JS implementation: https://www.npmjs.com/package/socket.io-msgpack-parser.

**Comment by zhavir** [comment]
what about implementing msgpack as the standard encoding also for the Redis emitter part? Now it seems that you cannot customize that part, then you cannot decouple the socket-io server from the client/emitter implementation due to the fact it uses by default the python pickling. In a complex architecture where each component are heterogeneous, having this strong constraint is bad in my opinion

**Comment by miguelgrinberg** [comment]
@zhavir your request is separate from this work, so I'm filing a separate issue for it: https://github.com/miguelgrinberg/python-socketio/issues/755
