### ISSUE TITLE
socketio.exceptions.ConnectionError: Unexpected response from server

### ISSUE THREAD

**Issue by AnanyaCS** [miguelgrinberg/python-socketio#833]
1.I have a flask_socketio app which is deployed on heroku. the flask app shows an index.html page when you call the url.

Config for flask app
Flask==2.0.2
gunicorn==20.1.0
eventlet==0.30.2
gevent-websocket==0.10.1
Flask-SocketIO==4.3.1
python-engineio==3.13.2
python-socketio==4.6.0

from flask import Flask, render_template, make_response, redirect
from flask_socketio import SocketIO, send, emit
import os
These are the imports in the flask server 

When i access this server deployed to heroku using a html+js app I can access it using cdn in script tag(from any html page basically)

But when i access it from python program I get unexpected response error. Providing full stacktrace here:

Attempting polling connection to https://my-server-raspi.herokuapp.com/socket.io/?transport=polling&EIO=4
Traceback (most recent call last):
  File "/home/pi/Desktop/test-project/client.py", line 4, in <module>
    sio.connect('https://my-server-raspi.herokuapp.com/')
  File "/home/pi/.local/lib/python3.9/site-packages/socketio/client.py", line 282, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected response from server

**Comment by miguelgrinberg** [comment]
Use the same version of python-socketio on the server and the client. The client version that you are using is not compatible with the much older version you have on the server.

Also, please don't raise bugs on this project when you are not sure what the problem is. There is a discussion board for that purpose. If you want to discuss this further, please start a discussion.
