### ISSUE TITLE
support statistics traffic

### ISSUE THREAD

**Issue by b23r0** [miguelgrinberg/python-socketio#942]
**Is your feature request related to a problem? Please describe.**

In my usage scenario, I need to count the traffic size of the transport layer in order to control the IO rate, but socketio cannot meet this requirement.

**Describe the solution you'd like**
I hope to add a variable of traffic statistics to the TCP socket IO, and to provide an interface to easily obtain the size of the transmitted traffic over a period of time, or from the establishment of the link to the present.

**Describe alternatives you've considered**
At present, I can only monitor traffic by capturing packets through raw sockets.

**Comment by miguelgrinberg** [comment]
I think this should be implemented at the transport level, the Socket.IO and Engine.IO layers do not deal with low-level sockets and do not keep track of bytes received/sent. The HTTP and WebSocket layers are better prepared to do this tracking, since they deal with bytes and not with high-level events as is the case in this package.

**Comment by b23r0** [comment]
As a user of socketio, I cannot intervene at the http or websocket layer. I think maybe socketio, as the wrapper of the http or websocket library, can consider intervening in the underlying library to facilitate traffic statistics.
