### ISSUE TITLE
Exception in MacOs while its working in Windows 10

### ISSUE THREAD

**Issue by suresh-j2** [miguelgrinberg/python-socketio#965]
**Describe the bug**
I'm trying to consume the socket.io used in https://pypi.org/project/breeze-connect/ and in MacOs its throwing the following error. 

`Traceback (most recent call last):
  File "/Users/suresh/PycharmProjects/icicialgo/Algo.py", line 64, in <module>
    breeze.ws_connect()
  File "/Users/suresh/PycharmProjects/icicialgo/venv/lib/python3.10/site-packages/breeze_connect/breeze_connect.py", line 52, in ws_connect
    self.sio_handler.connect()
  File "/Users/suresh/PycharmProjects/icicialgo/venv/lib/python3.10/site-packages/breeze_connect/breeze_connect.py", line 19, in connect
    self.sio.connect(self.hostname, headers={"User-Agent":"python-socketio[client]/socket"}, auth=auth, transports="websocket", wait_timeout=30)
  File "/Users/suresh/PycharmProjects/icicialgo/venv/lib/python3.10/site-packages/socketio/client.py", line 338, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection error`

The same code works well in Windows 10 without any change. 

python-engineio==4.3.1
python-socketio==5.5.2
 
The above is the version used.

**Comment by miguelgrinberg** [comment]
Hey, it seems you inadvertently omitted some information that is required when you file a bug. For your convenience, here is the details that you missed. Please provide these and I'll look at your problem. Thanks.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Please provide relevant logs from the server and the client. On the Python server and client, add the `logger=True` and `engineio_logger=True` arguments to your `Server()` or `Client()` objects to get logs dumped on your terminal. If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Additional context**
Add any other context about the problem here.

**Comment by sahasourav123** [comment]
faced similar issue i.e. python 3.x + socketio client connection failed on macos, but working in windows 11. Issue observed with Icici & kotak python client... however, able to find a workaround with javascript  + socketio.. issue not yet identified.

**Comment by miguelgrinberg** [comment]
@sahasourav123 if you can provide details to debug this, please open a new issue.
