### ISSUE TITLE
I don't know how to not report errors by not passing namespaces by default

### ISSUE THREAD

**Issue by baozaodetudou** [miguelgrinberg/python-socketio#982]
**Describe the bug**
I don't know how to not report errors by not passing namespaces by default

**To Reproduce**
```python
import asyncio
import socketio

sio = socketio.AsyncClient()

@sio.event
async def connect():
    print('connection established')

@sio.event
async def my_message(data):
    print('message received with ', data)
    await sio.emit('my response', {'response': 'my response'})

@sio.event
async def disconnect():
    print('disconnected from server')

async def main():
    await sio.connect("http://192.168.6.39:7777", socketio_path="ws")
    await sio.wait()

if __name__ == '__main__':
    asyncio.run(main())

```

**Expected behavior**
I want to connect normally

**Logs**
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mt/transform/test/client.py", line 20, in main
    await sio.connect("http://192.168.6.39:7777", socketio_path="ws", namespaces='/')
  File "/home/mt/venv/transform/lib/python3.9/site-packages/socketio/asyncio_client.py", line 163, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
python-BaseException
```

**Additional context**
![image](https://user-images.githubusercontent.com/37683726/181416384-c4212736-457d-462b-86df-4abe948dfd82.png)

**Comment by miguelgrinberg** [comment]
I'm not really sure what you are trying to tell me here with the code you are highlighting. If you found a bug, then please explain what the bug is. All I see is that you connected to a server and the server did not accept the connection.

**Comment by Satyamcoretus** [comment]
@miguelgrinberg 
suppose this is my class based namespace, here my motive is that i want to store the header information that i pass through the client, since i am building the chat-bot so ,there will be two entity other than server, (one is client and other is agent) 
here take a look , the way i am making the connection by client and by agent resp
`await sio.connect('http://192.168.0.53:8000',namespaces='/Chat',headers={'user' : 'client'})`
`await sio.connect('http://192.168.0.53:8000',namespaces='/Chat',headers={'user' : 'agent'})`
now in the server.py file 
instead of creating this connect event handler outside the class I put it into the class based namespace, 
by taking the reference of the documentation (take a look)
![image](https://github.com/miguelgrinberg/python-socketio/assets/165629167/dc471885-119a-4453-9d36-b18334c396f7)
the motive of doing is so that i can have 'client_id' as well as 'agent_id' stored as the class attributes

here take a look at my server.py file-
`import time
from Database.mongodb import Database
import socketio
import uuid
from socketio import AsyncNamespace
sio = socketio.AsyncServer(async_mode='asgi', logger=True,engineio_logger=True,ping_interval=50,cookie='satyam')    # ping_interval - after 50 seconds client will receive pong from server
app = socketio.ASGIApp(sio)`

`class ChatNamespace(AsyncNamespace):
    _client_sid = ''
    _agent_sid = ''
    _room_id = None
    _users = []
    _agent_num = None
    _last_sender = None
    _chat = []
    _user_messages = ""
    _agent_messages = ""`
    `async def on_connect(sid, environ):
        if environ:
            print(environ.get('HTTP_USER'))
            print(f'Client {sid} connected')
            print(f'Auth Data: {environ.get("auth")}')  # Access auth data
            print(f'Environment Variables: {environ}')`

please help, as I am new learning the web socket, do not know much about it, but trying my best to learn it quickly..
I appreciate your help
